### ISSUE TITLE
As a developer, I want the readme file to be updated, so that the issues identified in the artifact quality assessment are addressed to make artifact setup easier

### ISSUE THREAD

**Issue by ksamms1** [PappasBrent/maki#2]
- Technical requirements – Modification of the readme file to address the issues identified in the artifact quality assessment as well as any notable changes in feature #1.
- Initial assignments – Modify the readme file using the artifact quality assessment as a guide, and include any changes made from feature #1.
- Acceptance Criteria - Readme file includes the changes mentioned in the artifact quality assessment and addresses any changes from #1.
- Impact – 3/5. Moderately Important.  Modification to the readme file should clarify a few loose ends about artifact setup and thus make it easier for stakeholders to get started.
- Effort – 1/5. Easy.  Modifying the readme file is minor maintenance and shouldn’t take much time.
- Dependencies – feature #1 must be completed first.

**Comment by PappasBrent** [comment]
Also I think it would be appropriate if this issue also addressed how Maki's current documentation does not explain the output of its Clang plugin.
Right now one has to read Maki's associated paper to learn what Maki's output means; but there shuold be documentation internal to Maki that explains each of these properties.
It may also be worth adding a help message with these explanations also.

Also - while this repo contains the current state of Maki, there is no link to revised version of the artifact for ICSE 2024.

Adding this documentation will greatly help new users understand what Maki does, but writing them will require a deep understanding of the tool

**Comment by ksamms1** [comment]
This feature is closed as satisfied by task #5 (which has dependency on #1) which was satisfied by the closing of pull request #28.
